/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:878c3be4-89ee-49ba-a475-b4cda4c4aaaa',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_UhNeefUqh',
  aws_user_pools_web_client_id: '19qipfg9t1dkk4piu5jl6m85os',
  oauth: {},
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: ['REQUIRES_LOWERCASE', 'REQUIRES_NUMBERS', 'REQUIRES_SYMBOLS', 'REQUIRES_UPPERCASE']
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_appsync_graphqlEndpoint: 'https://ojpvemcsazb2xez6czprp3udp4.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-a3ltylbwszhyjbf4hqg2tk24qy'
}

export default awsmobile
